name: Harsha Seneviratne
favicon: null
layout_spectrum: 0.6265498967841268
typography_spectrum: 0.732939210254699
title: Actor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8176021964754909
  lightness: 0.46536392299458385
  saturation: 0.71169348154217
  rhythmicContrast: 0.8118350442964584
purpose: []
